### PR TITLE
Remove files for SDIO as it is now part of OpenWrt 21.02

### PR DESCRIPTION
**Pull request by BKPepe**
File brcmfmac43455-sdio.raspberrypi,4-compute-module.txt is now part of
``cypress-nvram-43455-sdio-rpi-4b`` package in OpenWrt 21.02.

Added in this commit: https://github.com/openwrt/openwrt/commit/a20e9474dfa0f98085ba595167624cad04086e67

So, this should be fine to merge as it is, because I see that in ``rpi_cm4_defconfig``, you requires the package to be installed.

```
configs/rpi_cm4_defconfig:CONFIG_DEFAULT_cypress-firmware-43455-sdio=y
configs/rpi_cm4_defconfig:CONFIG_DEFAULT_cypress-nvram-43455-sdio-rpi-4b=y
```

### CODE REVIEW

**Comment by lakshanthad** [comment]
I have compiled locally with your changes above. However, when I open Luci Web UI, the "Wireless" section is not there anymore. I will check it further. Do you also have any idea about that?

**Comment by BKPepe** [comment]
Is there anything in syslog? Did you compile it with [your's repository and openwrt-21.02 branch](https://github.com/Seeed-Studio/seeed-linux-openwrt/tree/openwrt-21.02)? You need to rebase it first to include the change from upstream.

**Comment by lakshanthad** [comment]
This is how the compilation was done:

git clone https://github.com/Seeed-Studio/seeed-linux-openwrt -b openwrt-21.02 openwrt
git clone https://github.com/Seeed-Studio/seeed-linux-openwrt -b magic config
cd openwrt
./scripts/feeds update -a
./scripts/feeds install -a
ln -s ../config/files/rpi/ files
cp ../config/configs/rpi_cm4_defconfig .config
make menuconfig
make -j16

**Comment by lakshanthad** [comment]
> Is there anything in syslog? Did you compile it with [your's repository and openwrt-21.02 branch](https://github.com/Seeed-Studio/seeed-linux-openwrt/tree/openwrt-21.02)? You need to rebase it first to include the change from upstream.
> 
> You can verify if you have installed package cypress-nvram-43455-sdio-rpi-4b and which files it has. These two commands will do it for you:
> 
> ```
> opkg list-installed | grep cypress-nvram-43455-sdio-rpi-4b
> opkg files cypress-nvram-43455-sdio-rpi-4b
> ```

Will check this

**Comment by BKPepe** [comment]
I see. Your repository does not include the upstream change. It needs to be rebased on top of openwrt-21.02 branch and then this can be merged.

**Comment by lakshanthad** [comment]
Please wait. I have manually run CI to merge with upstream. I will update my results here.

**Comment by lakshanthad** [comment]
Now it is merged with upstream and I have tested locally. It works. Thank you for the PR!

**Pull request merged**
